### ISSUE TITLE
can't archive coldarchive container

### ISSUE THREAD

**Issue by snigle** [ovh/manager#11645]
### Have you already contacted our help centre?

- [X] Yes, I have contacted the help centre.

### Is there an existing issue for this?

- [X] I have checked the existing issues

### Describe the bug

can't archive coldarchive container

### Steps To Reproduce

click on archive

### Expected Behavior

works

**Comment by anooparveti** [comment]
@snigle can you confirm that it's working fine now?

**Comment by anooparveti** [comment]
Closing the issue as no response from the reporter.
