### ISSUE TITLE
[manager-components]: Correcting content for <ManagerText

### ISSUE THREAD

**Issue by stif59100** [ovh/manager#12121]
### Have you already checked if a similar item is present on manager-components?

- [x] Yes, I have already checked the existing components/hooks/utils.

### What do you expect from this request?

Component

### Description

Hello,

just correcting the translation used on 
packages/manager-components/src/components/ManagerText/ManagerText.tsx
from 

     common_iam_actions_message
    to
       common_iam_get_message
    

Thanks

### Where do you expect to use this?

for use Iam on zimbra project

### Do you have mock-up?

no

### When do you expect this to be delivered?

na

### Additional Information

See with alex and guillaume

**Comment by acavalloni** [comment]
Already merged
