### ISSUE TITLE
Faute orthographe dans le panel Opérations en cours

### ISSUE THREAD

**Issue by pierr0t** [ovh/manager#12126]
### Have you already contacted our help centre?

- [X] Yes, I have contacted the help centre.

### Is there an existing issue for this?

- [X] I have checked the existing issues

### Describe the bug

Quand on va sur les "Opérations en cours", l'état de chaque opération passe à un moment donné par "plannifié" .... ça s'écrit "planifié", un seul "n" ... là je vois 11 fois la faute sur mon panel.

Référence: https://dictionnaire.lerobert.com/conjugaison/planifier

### Steps To Reproduce

Aller sur "Opérations en cours", onglet "Web cloud", menu "Opérations en cours" sous "Noms de domaine" dans le menu de gauche. Sur une opération aller tout à droite pour voir la colonne "Etat".

**Comment by anooparveti** [comment]
@pierr0t, thanks for reporting the issue. It must now be resolved.
