### ISSUE TITLE
[manager-component] Quantity Selector component

### ISSUE THREAD

**Issue by lionel95200x** [ovh/manager#12514]
### Have you already checked if a similar item is present on [manager-components](https://ovh.github.io/manager/storybook-static)?

- [X] Yes, I have already checked the existing components/hooks/utils.

### What do you expect from this request?

Component

### Description

Simple Quantity Selector without Ods Boilerplate

Update: Component design,

```
<ManagerQuantity
   value={}
   setValue={}
   min={}
   max={}
   step={}
   onChange={}
   disabled
/>
```

### Where do you expect to use this?

Savings Plans for the moment

### Do you have mock-up?

https://github.com/ovh/manager/blob/4a500578a22e2ef4adda97e128b4edb360888e0a/packages/manager/apps/pci-savings-plan/src/components/QuantitySelector/QuantitySelector.tsx

Update: Must match the existing component on ui-kit: https://ovh.github.io/ovh-ui-kit/?path=/docs/design-system-components-numeric-webcomponent--simple

### When do you expect this to be delivered?

_

**Comment by anooparveti** [comment]
@lionel95200x  ODS plans to simplify the usage in v18. So we will consider the issue after ODS upgrade to see if it's really required.

**Comment by anooparveti** [comment]
@lionel95200x ODSv18 already provides a simple OdsQuantity component. SO, we will not duplicate the implementation in favor of ODSv18.
https://ovh.github.io/design-system/latest/?path=/docs/ods-components-form-elements-quantity--technical-information
