### ISSUE TITLE
[manager-components]: Consider Tile as HTML input

### ISSUE THREAD

**Issue by SimonChaumet** [ovh/manager#12744]
### Have you already checked if a similar item is present on manager-components?

- [X] Yes, I have already checked the existing components/hooks/utils.

### What do you expect from this request?

Others

### Description

Make Tile a html input to allow usage of native html behaviors like :
- accessibility (https://developer.mozilla.org/en-US/docs/Learn/Forms/How_to_build_custom_form_controls#making_it_accessible)
- disabling with fieldset

### Where do you expect to use this?

PCI region selector

**Comment by anooparveti** [comment]
@aboungnaseng-ovhcloud to discuss with @SimonChaumet

**Comment by aboungnaseng-ovhcloud** [comment]
See with Simon no priority need for this topic, the need its not clear by the ux team, we can close the ticket
