### ISSUE TITLE
[manager-components]: <Clipboard> display text on hover 

### ISSUE THREAD

**Issue by seven-amid** [ovh/manager#12903]
### Have you already checked if a similar item is present on manager-components?

- [X] Yes, I have already checked the existing components/hooks/utils.

### What do you expect from this request?

Component

### Description

For the actual Clipboard, we need to display text on hover, just as it is displayed on the production Clipboard.

### Where do you expect to use this?

k8s app

**Comment by aboungnaseng-ovhcloud** [comment]
For the onHover state, the new version ODS 18 will have this feature 'labelCopy'

**Comment by anooparveti** [comment]
Already available on ODSv18 and we will be deprecating the Clipboard component in MRC v3.
Refer: https://ovh.github.io/design-system/latest/?path=/docs/ods-components-clipboard--technical-information

And for maintaining the common translations, control tower will be adding a new package.
