### ISSUE TITLE
[manager-components]: <GuidesHeader> some menu of kubernetes guides link to undefind

### ISSUE THREAD

**Issue by seven-amid** [ovh/manager#12912]
### Have you already checked if a similar item is present on manager-components?

- [X] Yes, I have already checked the existing components/hooks/utils.

### What do you expect from this request?

Component

### Description

For example, when the subsidiary is FR and the guide doesn't have the entry key 'FR,' the link will be undefined. Therefore, we should handle this case by linking to the DEFAULT URL instead.

Here is an example of a PR that I canceled because I should go through GitHub for these kinds of requests.
https://github.com/ovh/manager/pull/12905

### Where do you expect to use this?

K8S microApp

### Additional Information

it's a QA return mentioned as blocker, so we should fix it before going to production
this is the Jira ticket DTCORE-2530

**Comment by aboungnaseng-ovhcloud** [comment]
Its ok for the Pr, you van re-open the PR and target "develop" branch or if release Prod next week is urgent you can merge it in your 'epic' branch

**Comment by seven-amid** [comment]
Thank you, Alex. I will re-open it and merge it into our epic branch. We'll need to regenerate a staging environment afterward for QA test confirmation.

**Comment by anooparveti** [comment]
@seven-amid there are comments on your PR. Can you please check and fix it.
Also, can you rebase your branch with develop so that it will be quick to handle it?

**Comment by seven-amid** [comment]
@anooparveti  This PR is needed for a staging build, QA revalidation, and a production release planned for next week, so the process of splitting it into two PRs is quite cumbersome. One PR would contain only the fix on manager-component, then review and merge it into develop, then rebase feat/manager-pci-common with develop, followed by feat/pci-kubernetes with feat/manager-pci-common. After all that, a second PR would need to be created to update the test snapshots. I find it quite heavy to do this for every small fix on manager-component ( specially when it concerne the PCI staff ).

I suggest merging it directly into the epic branch ( feat/pci-kubernetes ) for all these reasons. what do u think :)

**Comment by anooparveti** [comment]
Already merge with #13128
