### ISSUE TITLE
[manager-react-components]: useResourcesIcebergV6 bugs : Duplicate result on multiple use

### ISSUE THREAD

**Issue by tibs245** [ovh/manager#13331]
### On which entity, you would like to report a bug?

hooks/useResourcesIcebergV6

### Description

Fix useResoucesIceberg because when I read the code we can see if 2 components call this useResoucesIceberg or we go back on page with the same app we trigger more one time fetchNextPage.

So we have multiple same data in result. Multiple same pages on data.

### Steps to reproduce

Use this hook on two separated components.
Or re-create component or pages use it more one time on instance app

### Operating System

- [X] macOS
- [X] Windows
- [X] Linux

**Comment by aboungnaseng-ovhcloud** [comment]
Done 👍
