### ISSUE TITLE
[manager]: use react-hook-form & validation library

### ISSUE THREAD

**Issue by tristanwagner** [ovh/manager#13395]
### Have you already checked if a similar item is present on manager-components?

- [X] Yes, I have already checked the existing components/hooks/utils.

### What do you expect from this request?

Others

### Description

To have a clean way of handling forms and do data validations via schemas we would like to use in zimbra a new dependency [react-hook-form](https://react-hook-form.com/) along with a schema validating library for example [zod](https://github.com/colinhacks/zod), [joi](https://joi.dev/) or [yup](https://github.com/jquense/yup). These are widely used and a must have for form handling and data validation with type inference etc.. Can we discuss about this ?

### Where do you expect to use this?

@ovh-ux/manager-zimbra-app

### When do you expect this to be delivered?

ASAP

**Comment by aboungnaseng-ovhcloud** [comment]
- agre for react-hook-form we already use this in pci universe

**Comment by aboungnaseng-ovhcloud** [comment]
Lets share with the team the differents packages 

- zod,
- joi
- yup

As I never use theses components, you can share a commesage to the react js channel to have some user experience.

The only things we have to be careful its about the size of app and we need to have the same coding style inside the manager, to not have a lot of differences beetween react app, (more easy to review, more easy to debug ...)

**Comment by anooparveti** [comment]
`zod` is accepted as the schema validation library and is added to the list of whitelisted libraries.
