### ISSUE TITLE
[manager-components]: fix IAM check for urn with special characters

### ISSUE THREAD

**Issue by chipp972** [ovh/manager#13392]
### On which entity, you would like to report a bug?

useAuthorizationIam

### Description

If you pass an urn with "/" (like a virtualDataCenter urn) the authorization check returns a 404 since the url is falsed by the urn.

### Steps to reproduce

Use a ManagerButton or ManagerText with an urn containing "/" character

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by aboungnaseng-ovhcloud** [comment]
PR in waiting for merge 👍
