### ISSUE TITLE
[manager-components]: DataGridTextCell is rendered with wrong font size

### ISSUE THREAD

**Issue by fredericvilcot** [ovh/manager#13606]
### On which entity, you would like to report a bug?

components/datagrid/text-cell.component.tsx

### Description

Since this [commit](https://github.com/ovh/manager/commit/856e07e9308f3cf7c69ad49280e78eca45b9b809#diff-d7413232cb729284571b3eff373b4bf8ca3758830e677b480f0cf4cd0d5b6807R26), all data grids using `DataGridTextCell` component have now a 14px of font-size (it was 16px before)

### Steps to reproduce

Ovh manager > Public Cloud > Managed Rancher Service 

The list items Service Plan, Rancher Version and number of vCPUs are displayed with a 14px font-size

### Browser

Firefox

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by acavalloni** [comment]
Hello Frederic ! Thanks for the feedback (and the the sharp eye).
In fact, it is not an issue as it has been asked by Design team to match Design system guideline.
