### ISSUE TITLE
[manager-components]: Add hook for navigation getUrl

### ISSUE THREAD

**Issue by tibs245** [ovh/manager#13649]
### Have you already checked if a similar item is present on manager-components?

- [X] Yes, I have already checked the existing components/hooks/utils.

### What do you expect from this request?

Component

### Description

Today when we need get Url from navigation it's not easy :

Here a extract code of KMS:

`packages/manager/apps/key-management-service/src/components/layout-helpers/Dashboard/GeneralInformationsTiles/BillingInformationsTile.tsx`

```ts
const [contactUrl, setContactUrl] = useState('');
  const {
    shell: { navigation },
  } = useContext(ShellContext);
  
  
    useEffect(() => {
    const fetchUrl = async () => {
      try {
        const response = await navigation.getURL(
          'dedicated',
          '#/contacts/services',
          {},
        );
        setContactUrl(response as string);
      } catch (error) {
        setContactUrl('#');
      }
    };
    fetchUrl();
  }, [navigation]);
```

And after we can use contactUrl without informations on the loading and error state.

So we have TanStack Query to facilitate promise management. And in finallity possibility just use : 

```ts
 const { data: contactUrl } = useNavigationGetUrl(['dedicated', '#/contacts/services', {}];
```

### Where do you expect to use this?

hycu

### Do you have mock-up?

No

### When do you expect this to be delivered?

31-10-2024

**Comment by anooparveti** [comment]
The request will be tackled with MANAGER-15760
