### ISSUE TITLE
[manager-components]: Custom serviceName or DisplayName on service dashboard

### ISSUE THREAD

**Issue by stif59100** [ovh/manager#14296]
### Have you already checked if a similar item is present on manager-components?

- [X] Yes, I have already checked the existing components/hooks/utils.

### What do you expect from this request?

Component

### Description

Hello,

Currently in the following applications:
@ovh-ux/manager-web-app on hosting
@ovh-ux/manager-dedicated-app on managedBare metal server
@ovh-ux/manager-office-app
etc etc

When we go to the ServiceName page, we have a component that allows us to custom the service name. from serviceName to displayName

example on web hosting
![image](https://github.com/user-attachments/assets/a0e4b5f6-295a-40aa-8bd7-760dd267903c)
![image](https://github.com/user-attachments/assets/5ced4a66-4598-4422-8ea9-74a39bc78c57)

### Where do you expect to use this?

web-office

### Do you have mock-up?

no

### Additional Information

This component would be required as part of the migration of the office en react application

**Comment by anooparveti** [comment]
@stif59100 to check with PO to align the behavior with other products by using `UpateNameModal` component already existing on MRC.
