### ISSUE TITLE
Standalone applications cannot be started

### ISSUE THREAD

**Issue by antleblanc** [ovh/manager#1628]
**Describe the bug**
I'm trying to launch some standalone applications like:

- @ovh-ux/manager-freefax
- @ovh-ux/manager-overthebox
- @ovh-ux/manager

But the console reported me this following:

```js
Uncaught TypeError: _ovh_ux_manager_config__WEBPACK_IMPORTED_MODULE_0__.Environment.getVersion is not a function
    at eval (index.js:5694)
    at Object.invoke (angular.js:5141)
    at eval (angular.js:4940)
    at forEach (angular.js:387)
    at createInjector (angular.js:4940)
    at doBootstrap (angular.js:1960)
    at bootstrap (angular.js:1981)
    at angularInit (angular.js:1866)
    at HTMLDocument.eval (angular.js:36430)
    at fire (eval at module.exports (addScript.js:NaN), <anonymous>:3187:31)
``` 

**To Reproduce**
1. Go to a standalone application location (e.g.: `packages/manager/apps/freefax`)
2. Run `yarn run start:dev`
3. See error

**Expected behavior**
Standalone application must work.

**Additional context**
Seems related to #1525

**Comment by FredericEspiau** [comment]
This is the error reported by @AxelPeter on Friday 25th of October 2019

**Comment by antleblanc** [comment]
@FredericEspiau Thanks for pointing out.

I think it was more about an issue with `@ovh-ux/manager-web` package (circular dependency) which has already be fixed by theses following commits:

- https://github.com/ovh/manager/commit/223dd9cc9e47bb66a3f9fce4ac9c86a873c71c15
- https://github.com/ovh/manager/commit/b2f03c1c31fd27c78be8ec87a27a3b3935892156
- https://github.com/ovh-ux/ovh-angular-responsive-page-switcher/commit/22c62d8c321f49d442922cbc07101eeb2bc4767d
