### ISSUE TITLE
advanced settings translations

### ISSUE THREAD

**Issue by tadhglewis** [ovh/manager#2025]
**Describe the bug**
- 1. manager/packages/manager/modules/beta-preference/src/translations should include English translations (and all other languages, not sure if they are all added in at once in the internal process) as it currently shows French in the beta features section when using English
- 2. manager/packages/manager/apps/dedicated/client/app/account/user/translations user_account_advanced_section_developer_component_library should include space between 'our' and 'library' (in English translations and in most other Languages

**To Reproduce**
- 1. Go to My Account > Advanced Settings > Fonctionnalités Bêta
- 2. Go to My Account > Advanced Settings > Options for developers > Access our componentlibrary

**Expected behavior**
- 1. View English translations
- 2. Should include space

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
for reference https://github.com/ovh/manager/pull/2024

**Comment by antleblanc** [comment]
Thanks @tadhglewis for reporting this issue.

I have create a new translations request where I mentioned your original Pull Request.
It will be handle by our Translations team.

I will keep you posted as soon as the translations are fixed.

Thanks!

**Comment by antleblanc** [comment]
@tadhglewis!

Now fixed on `develop` branch.
see: https://github.com/ovh/manager/commit/ccc5e5c80c99443c90d6c6f703de6c4289c783f8

I will add it to the next release and keep you posted as soon as it's deployed.

Thanks!

**Comment by tadhglewis** [comment]
Cheers @antleblanc
