### ISSUE TITLE
Translations for cPanel order a licence

### ISSUE THREAD

**Issue by tadhglewis** [ovh/manager#2036]
**Describe the bug**
No translations for `2. Select your options` dropdowns on order a licence page for cPanel

**To Reproduce**
- Go to Dedicated/Server > Licences > Order > Select IP Block > Select cPanel > See Dropdown

**Screenshots**
![image](https://user-images.githubusercontent.com/53756558/71757720-0a687980-2eec-11ea-8152-554cd6e55ea7.png)

**Additional context**
Translations required.
This may also be an issue with manager/packages/manager/apps/dedicated/client/app/license/order/license-order.html line 136

**Comment by antleblanc** [comment]
Hi @tadhglewis!

Thanks for reporting this issue.
I will keep you posted as soon as I have updates.

**Internal ticket reference**: MANAGER-4254
