### ISSUE TITLE
Cannot install a new module!

### ISSUE THREAD

**Issue by nouraellm** [ovh/manager#2058]
**Add a module button is not working**
Cannot install new module such as: WordPress or Prestashop using the manager, after clicking the add a module button, you keep waiting for minutes but nothing happens, and the module is not created.

**Desktop:**
 - OS: Mac
 - Browser: Chrome
 - Version: last version

**Comment by antleblanc** [comment]
Hi @nouraellm!

Thanks for reporting this issue.

I made a few tests and I'm able to install a new module.

Is the following information displayed right after clicking on "Install"?

![screenshot](https://user-images.githubusercontent.com/428384/72047362-a6aec980-32ba-11ea-8094-e0d719384b43.png)

Did you receive an email?

**Comment by nouraellm** [comment]
Hi @antleblanc 

The issue has been fixed and now I'm able to install a module, as well the information is being displayed right after the installation. 

Thank you!
