### ISSUE TITLE
issue: error on windows installation 'MODULE_NOT_FOUND'

### ISSUE THREAD

**Issue by fchabrolle** [ovh/manager#2134]
Following the documentation on :  https://ovh.github.io/manager/guide/getting-started.html#prerequisites
After yarn install i get the error

error C:\Users\<USERNAME>\Documents\projects\manager\node_modules\@ovh-ux\component
-rollup-config: Command failed.
Exit code: 1
Command: yarn run build
Arguments:
Directory: C:\Users\fchabrol\Documents\manager\manager\node_modules\@ovh-ux\comp
onent-rollup-config
Output:
yarn run v1.21.1
$ tsc
internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module 'C:\Users\<USERNAME>\Documents\projects\node_modules\type
script\bin\tsc'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
error Command failed with exit code 1.

Desktop
 - OS: windows 10
- Node.js 12.13.1
- yarn v1.21.1

**Comment by antleblanc** [comment]
Thanks @fchabrolle for reporting this issue.

I've recently notice this error and it seems to be related to the `postinstall` hook which is used in the following workspace: `packages/manager/tools/`.

We will take a closer look.
