### ISSUE TITLE
Component Rollup Configuration - Translation inject with inline comment

### ISSUE THREAD

**Issue by antleblanc** [ovh/manager#2218]
**Describe the bug**
Translations are still injected even if the annotation is commented.

**To Reproduce**
1. Comment a `.run(/* @ngTranslationsInject:json ./translations */)` annotation.

```js
import angular from 'angular';
import component from './component';

const moduleName = 'moduleName';
angular
  .module(moduleName, [])
  .component('componentName', component);
//   .run(/* @ngTranslationsInject:json ./translations */);

export default moduleName;
````

2. Build the application.
3. Take a closer look to the generated chunks in a `dist` folder 
4. See the Issue.

**Expected behavior**
Translations must not be injected if the annotation commented.

**Additional context**
Probably related to the `onComment` option that cannot tell if the line starts with inline comment `//`.

cc @frenautvh

**Comment by FredericEspiau** [comment]
😅

**Comment by frenautvh** [comment]
@antleblanc damn! i'll take a look

**Comment by antleblanc** [comment]
Closing this issue.
