### ISSUE TITLE
Display only available product categories in Sidebar

### ISSUE THREAD

**Issue by cbourgois** [ovh/manager#2360]
**Is your feature request related to a problem? Please describe.**
Currently we display all product categories in the sidebar even if the customer don't have products in theses categories. Services are retrieved when the user clicks on it, and if he don't have services for this product category we display a message "_No services_"

**Describe the solution you'd like**
We should add the possibility to build the sidebar depending on the customer's services.
As discussed in #2291, a solution envisaged is to have an api that returns the number of services by product categories to help us to initialize the sidebar with customer's products categories only.

**Additional context**
A first pull request add this functionality by loading all customers services (#1833 by @julieni), but for some users it affects performances. A revert was proposed to apply the first approach (#2291).

**Comment by JeremyDec** [comment]
Hello @cbourgois, as seen together, closing issue
