### ISSUE TITLE
Translates errors (Dedicated & Public Cloud)

### ISSUE THREAD

**Issue by SimonRTC** [ovh/manager#2444]
**Describe the bug**
Translate error

**To Reproduce**
1. Go to 'https://www.ovh.com/manager/dedicated/index.html#/billing/history'
2. Click on 'Recevoir mes factures au format papier'
4. See error (Le paramètre a bien été mis à jour. **Vous ne recevrez plus** vos factures au format papier.)

**Screenshots**
[See here](https://i.ibb.co/L9JXcLT/Capture-d-e-cran-2020-03-09-a-17-16-43.png)

---

**Describe the bug**
Translate error

**To Reproduce**
1. Go to 'https://www.ovh.com/manager/public-cloud/index.html#/pci/projects/default/kubernetes/{KubeId}/containers'
2. Click on 'Recevoir mes factures au format papier'
4. See error (Nous vous invitons à utiliser l'outil en ligne de commande "kubectl" ou installer le **Daskboard** Kubernetes.)

**Screenshots**
[See here](https://i.ibb.co/JC5sZMy/Capture-d-e-cran-2020-03-09-a-17-21-33.png)

**Comment by antleblanc** [comment]
Hello @SimonRTC!

We will investigate. We also keep you posted as soon as the patch is available.

Thanks!
