### ISSUE TITLE
Installation Impossible

### ISSUE THREAD

**Issue by Dono52** [ovh/manager#2711]
Bonjour, je voudrais savoir pourquoi c'est impossible d'installer le Manager en 2020 ?

**Comment by antleblanc** [comment]
Bonjour @Dono52 !

Avez-vous une erreur qui est remontée lors de l'installation de l'espace client ?

Si oui, pouvez-vous nous laisser une trace de celle-ci afin de nous aider à reproduire
le cas et apporter une correction ?

Merci

**Comment by Dono52** [comment]
J'ai une erreur avec Yarn qui dis impossible de faire le truc de "Install"

**Comment by Dono52** [comment]
**J'ai ça :** 
[BABEL] Note: The code generator has deoptimised the styling of /root/manager/packages/manager/modules/navbar/dist/esm/index.js as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /root/manager/packages/manager/modules/cloud-universe-components/dist/cjs/index.js as it exceeds the max of 500KB.

**Comment by Dono52** [comment]
Et impossible d'installer NVM sur LXC

**Comment by antleblanc** [comment]
@Dono52 l'application est accessible via le port `9000` par défaut.

Nous avons récemment mis a jour la documentation ici :
https://ovh.github.io/manager/guide/applications.html#web

Pouvez-vous me confirmer que l'application démarrer correctement sur votre environnement ?

Merci

**Comment by Dono52** [comment]
Non l'application reste bloquer sur @ovh-ux/manager-web: DONE Compiled successfully in 107735ms9:48:57 PM et ne démarre pas après ça

**Comment by antleblanc** [comment]
Pouvez-vous me retourner le résultat de la commande :

```sh
$ curl -I http://localhost:9000
```

Merci

**Comment by Dono52** [comment]
**Voici** : curl: (7) Failed to connect to localhost port 9000: Connection refused

**Comment by antleblanc** [comment]
L'erreur montre un problème de connexion sur le port `9000`. Ce port est-il accessible ?

La commande suivante peut vous aider a lister tous les ports restreints par service:

```sh
semanage port -l
```

Ressource : https://www.certdepot.net/rhel7-use-selinux-port-labelling/

**Comment by Dono52** [comment]
J'ai l'erreur la ; 

Traceback (most recent call last):
  File "/usr/sbin/semanage", line 28, in <module>
    import seobject
  File "/usr/lib/python3/dist-packages/seobject.py", line 1039, in <module>
    class portRecords(semanageRecords):
  File "/usr/lib/python3/dist-packages/seobject.py", line 1041, in portRecords
    valid_types = list(list(sepolicy.info(sepolicy.ATTRIBUTE, "port_type"))[0]["types"])
  File "/usr/lib/python3/dist-packages/sepolicy/__init__.py", line 196, in <genexpr>
    return ({
  File "/usr/lib/python3/dist-packages/setools/typeattrquery.py", line 65, in results
    for attr in self.policy.typeattributes():
AttributeError: 'NoneType' object has no attribute 'typeattributes'


quand je fait la commande : semanage port -l

**Comment by Dono52** [comment]
**J'ai ouvert le port avec :** iptables -A INPUT -p tcp -i eth0 --dport 9000 -j ACCEPT

**Comment by Dono52** [comment]
Il y a Apache2 par defaut sur la machine je le laisse ?

**Comment by Dono52** [comment]
Je voulais savoir si ça c'est normal : https://media.discordapp.net/attachments/694934997458747433/695263602386665542/Erreur.PNG?width=760&height=427

**Comment by Dono52** [comment]
https://media.discordapp.net/attachments/694934997458747433/695266273692745758/Erreur2.PNG?width=760&height=427

**Comment by Dono52** [comment]
Logs Yarn : http://51.158.89.216/yarn-error.log

**Comment by Dono52** [comment]
Comment changer ça :
[BABEL] Note: The code generator has deoptimised the styling of /root/manager/packages/manager/modules/navbar/dist/esm/index.js as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /root/manager/packages/manager/modules/cloud-universe-components/dist/cjs/index.js as it exceeds the max of 500KB.

**Comment by Dono52** [comment]
Local C'est OK maintenant mes impossible d'y acceder depuis l'ip

**Comment by Dono52** [comment]
curl -I http://localhost:9000 = 
HTTP/1.1 200 OK
X-Powered-By: Express
Accept-Ranges: bytes
Content-Type: text/html; charset=UTF-8
Content-Length: 2217
ETag: W/"8a9-RVjvR9BI8znKBQUEkaGaZHQkLyk"
Date: Fri, 03 Apr 2020 11:29:44 GMT
Connection: keep-alive

**Comment by antleblanc** [comment]
Pouvez-vous m'indiquer si l'espace client se charge correctement depuis l'adresse `http://localhost:9000`?

En cas de problème d'affichage pouvez-vous joindre une capture écran de votre navigateur (avec la console ouverte au besoin).

Toutefois n'hésitez pas à compléter les informations suivantes afin de nous aider à reproduire les erreurs rencontrées :

- Environnement sur lequel le projet a été installé (OS)
- Version de Node.js
- Version de Yarn
- Commandes exécutées
- etc

Merci pour vos retours

**Comment by Dono52** [comment]
Je ne sais pas si l'espace ce charge je suis sur un linux sans interface bureau

**Comment by Dono52** [comment]
Avec l'espace client on peut faire quoi aussi ?

**Comment by antleblanc** [comment]
L'espace client OVHcloud (Manager) est une interface permettant de gérer notamment son catalogue de produits ainsi que son compte client.

Cette interface repose sur l'API publique : https://api.ovh.com/.

L'administration de cette espace client n'est pas liée à interface dédié.

Toute modification de cette dernière est rendu possible via la contribution au code source (voir https://github.com/ovh/manager/blob/master/CONTRIBUTING.md).

**Comment by Dono52** [comment]
D'accord mes comment faire pour aider au code ?

**Comment by antleblanc** [comment]
Pour aider au code vous pouvez utiliser le menu [Pull Requests](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests).

Nous nous ferons un plaisir d'intégrer vos contributions 🙂
