### ISSUE TITLE
subaccounts: password reset dialog shows wrong email address

### ISSUE THREAD

**Issue by FlorianLudwig** [ovh/manager#3015]
**To Reproduce**
1. Login with a sub account
2. Click change password
3. Dialog appears: "An email will be sent to the XXXX..." where X is the email address of the main account, not the sub account.
4. The email arrives at the right email address

**Expected behavior**
Show corret email address

**Comment by antleblanc** [comment]
@FlorianLudwig The patch will be deployed on the Production environment on August 6th.
I will keep you posted, thank you!

**Comment by antleblanc** [comment]
@FlorianLudwig The patch has been deployed! Thank you!
