### ISSUE TITLE
kubernetes node overview does not handle quota case

### ISSUE THREAD

**Issue by FlorianLudwig** [ovh/manager#3017]
**Describe the bug**
UI is not readable when hitting quota.

**To Reproduce**
1. Create new cloud project (with low quota)
2. Create new kubernetes cluster
3. Order nodes until quota is hit
4. get unreadable error (and have no idea it is the quota you have hit)

**Expected behavior**

Get proper error or better be not able to order node in first place.

**Screenshots**

![image](https://user-images.githubusercontent.com/432263/83010953-60fc5e80-a019-11ea-9137-20f20120e4b5.png)

With the help of the support we figured out "kube_nodes_status_US" is "kube_nodes_status_USER_QUOTA_ERROR"

**Comment by antleblanc** [comment]
Thanks @FlorianLudwig for reporting this issue.

We will keep you posted as soon as a patch will be deployed.

**Comment by antleblanc** [comment]
@FlorentinDUBOIS Patch has been deployed. It's now fixed!
