### ISSUE TITLE
[Kubernetes] Node naming form validation outdated

### ISSUE THREAD

**Issue by XavierDuthil** [ovh/manager#3065]
**Describe the bug**
When entering the Instance name for a new Kubernetes node and typing a name with an unauthorized character, such as `_`, the following validation error message appears:
> The instance name must begin and end with lower-case alphanumeric characters (a to z and 0 to 9) and may include the following punctuation marks:". "and" -".

It clearly indicates that the `.` character is authorized, however when adding a node with a name including this character, such as `node1-1.17`, the form validates but the following error is then displayed on the main Manager form:
> An error has occurred adding the node: 400: Node name node1-1.17 is invalid

**To Reproduce**
1. Go to the 'Public cloud' section
2. Go to the Managed Kubernetes Service subsection
3. Click on an existing Kubernetes cluster
4. Go to Nodes
5. Click `Add node`
6. Enter the following name: `node1-1.17` (optional: enter an `_` character to see the validation error message)
7. Complete the rest of the form
8. Click `Add`

**Expected behavior**
No error message when entering a character which is specified as valid.

**Screenshots**
![image](https://user-images.githubusercontent.com/31845024/83621702-4e40d700-a58f-11ea-8577-50ed62c5f42b.png)
![image](https://user-images.githubusercontent.com/31845024/83621746-5d278980-a58f-11ea-9506-539698b53c76.png)

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Firefox
 - Version: 73.0.1

**Comment by mhurtrel** [comment]
in fact "." are not supported in the nodes/nodepool name in APIv6. The frontend regex/hint should be updated by saying that . are unsuppoorted

**Comment by mhurtrel** [comment]
Confirmed the bug is fixed on the staging environnement given by @antleblanc

**Comment by antleblanc** [comment]
@XavierDuthil The patch will be deployed on the Production environment on August 6th.
I will keep you posted, thank you!

**Comment by antleblanc** [comment]
@XavierDuthil The patch has been deployed in production! Thank you!
