### ISSUE TITLE
new lang to cp

### ISSUE THREAD

**Issue by SukiIto** [ovh/manager#3244]
**Is your feature request related to a problem? Please describe.**
 I'm always frustrated when i can't change language to Russian

**Describe the solution you'd like**
I want the Russian language to appear in the control panel, so that I would be more comfortable using the service.

**Describe alternatives you've considered**
Add Russian to the list of languages ​​available for selection
**Additional context**

**Comment by antleblanc** [comment]
Hi @SukiIto!

We currently provide 10 languages which are:
- Deutsch
- English
- Español
- Français
- Français (Canadien)
- Italiano
- Lietuviškai
- Polski
- Português
- Suomi

Having the *Russian* is not plan yet so I'm sorry to inform you that it won't be available.

Thank you!
