### ISSUE TITLE
Interface labeling issue (in Database tab)

### ISSUE THREAD

**Issue by EmbDclic** [ovh/manager#3248]
**Describe the bug**
The labels of 2 elements are incorrect.

**To Reproduce**
1. Go to the Database tab of a web hosting.
2. Click on the 3 dots button on the right of a database.

**Expected behavior**
Have readable lables.

**Screenshots**
![image](https://user-images.githubusercontent.com/23118296/87319416-e1bfdd00-c529-11ea-8368-88b9d2f44c51.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 83

**Comment by antleblanc** [comment]
Thank you @EmbDclic for pointing out this bug.

I opened a [Pull Request](#3265) to solve this issue.
We will keep you posted as soon as the patch is deployed.

Thank!

**Comment by antleblanc** [comment]
@EmbDclic Patch has been deployed!
