### ISSUE TITLE
Valid Canadian phone number marked as invalid

### ISSUE THREAD

**Issue by mdavranche** [ovh/manager#3249]
**Describe the bug**
Valid Canadian phone number marked as invalid.

**To Reproduce**
On the Canadian Control Panel,
1. Create a new account and fill the 8556845463 phone number (mark it as Canadian) or change your phone number with 8556845463 (mark it as Canadian).
2. See that is is marked as invalid. It definitely is (that's the OVHcloud Canadian number).

You can also try with 8556845462, that is valid and that is not the OVHcloud one.

**Expected behavior**
Accept the phone number, a valid one.

**Screenshots**
![Screenshot_2020-07-13 OVHcloud](https://user-images.githubusercontent.com/12912247/87344206-01e89f80-c51c-11ea-8a9f-23eb37e10870.png)

**Desktop:**
 - OS: Ubuntu 20.04
 - Browser: Firefox 78.0.1

**Additional context**
In north America, knowing if a phone number is valid or not is quite complex (See [the rules just for the 3 first digits](https://en.wikipedia.org/wiki/List_of_North_American_Numbering_Plan_area_codes)). My suggestion would be to use a (very) up-to-date lib to do that (do not try to do it yourself), or be more permissive.

**Comment by marie-j** [comment]
Hello @mdavranche 

Thank you for pointing out this issue and sorry for the delay of response.
The manager application doesn't handle the validation rules so I have contacted the right team internally to notify them

**Comment by marie-j** [comment]
Hello @mdavranche, 

A patch has been deployed therefore I'll close this issue. Feel free to re-open if you are still able to reproduce it. 

Thanks
