### ISSUE TITLE
Adding a naked debian 10 installation template

### ISSUE THREAD

**Issue by dcaillibaud** [ovh/manager#3489]
Since debian 10, the ovh template has a lot of cloud stuff in it, not really wanted in a lot of case for a baremetal server.

Could you provide a naked debian (like on after a debootstap install) ? It'll save few hours to many users ;-)

**Comment by antleblanc** [comment]
Hi @dcaillibaud! Thanks for reporting us this **Feature Request**.

We used to have a _naked_ Debian image but it has been replaced by the default one.
see: https://cloud.debian.org/images/cloud/OpenStack/

According to our documentation, you can rely on a specific image _(if needed)_.
see: https://docs.ovh.com/gb/en/dedicated/bringyourownimage/

Through our **API Console** you have the ability to provide your own image.

Currently we are implementing this feature directly into the Control Panel (#4103 ).
The development is underway and we will keep you posted once it will be released.

Thank you!

**Comment by antleblanc** [comment]
Hi @dcaillibaud!

We will keep you posted once the release will be deployed.

Thank you!

**Comment by antleblanc** [comment]
Hi @dcaillibaud!

The feature has been deployed in both EU (`ovh.com/manager/`) and CA (`ca.ovh.com/manager/`) region.

![screenshot](https://user-images.githubusercontent.com/428384/105826285-dd887800-5fc0-11eb-91df-2d293dfd4220.png)

You now have the new option "Install from custom image".

Here is our documentation: https://docs.ovh.com/gb/en/dedicated/bringyourownimage/

Will be soon deployed in the US (`us.ovhcloud.com/manager/`) region.

Thank you!
