### ISSUE TITLE
[Kubernetes] Loading flavors

### ISSUE THREAD

**Issue by Kafei59** [ovh/manager#3558]
**Describe the bug**
Flavors loading is not done correctly, there are two calls to be done:
1. If we want to load flavors for node pool creation BEFORE (in fact, during) cluster creation, everything is correct, this is the right call: 
```js
  getKubeFlavors(region, projectId) {
    return this.$http.get(
      `/cloud/project/${projectId}/capabilities/kube/flavors`,
      {
        params: {
          region,
        },
      },
    ).then((response) => response.data);
  }
```
2. But, when the cluster is already CREATED and we want to create a new node pool for example, we need to use this endpoint: 
```
/cloud/project/${projectId}/capabilities/kube/${kubeId}/flavors
```

**Expected behavior**
We need to implement this call, otherwise, we are blocking a feature for our specific customers (allowing only one specific flavor for a customer)

**Comment by marie-j** [comment]
https://github.com/ovh/manager/releases/tag/technetium-dinosaur-1
