### ISSUE TITLE
IP Restrictions: do not allow customer to lock them outise

### ISSUE THREAD

**Issue by Alkorin** [ovh/manager#4052]
On the user account security page, if the default rule is "deny", do not allow the customer to remove the last IP, else it will be blocked outside without any access to his account.

Maybe display an info popup which says that the default rule is "deny" and ask to change it to "allow" before deleting the last IP

**Comment by antleblanc** [comment]
@Alkorin patch has been merged. It will be part of the next release.
I will keep you posted once it will be deployed.

Thank you!
