### ISSUE TITLE
Problem with the manager when i try to go to dashboard, ips or etc.

### ISSUE THREAD

**Issue by Knife015** [ovh/manager#4064]
The loading bar on top is to slow but when i try to go at https://ca.ovh.com/manager/ this load to fast

I use the last versión on chrome, Windows 10 Pro, Version 20H

Protocol error (Network.setBlockedURLs): :// is not a valid URL
```
Channel: DevTools
Initial URL: https://ca.ovh.com/manager/dedicated/#/iaas/vps/vps-300c4618.vps.ovh.ca/dashboard
Chrome Version: 86.0.4240.198
Stack Trace: Error: Protocol error (Network.setBlockedURLs): :// is not a valid URL
    at Function.fromProtocolMessage (devtools://devtools/remote/serve_file/@d8a506935fc2273cfbac5e5b629d74917d9119c7/lighthouse_worker/lighthouse_worker_module.js:2041:121)
    at eval (devtools://devtools/remote/serve_file/@d8a506935fc2273cfbac5e5b629d74917d9119c7/lighthouse_worker/lighthouse_worker_module.js:1553:246)
```

https://gyazo.com/70ff05315ed0a39583122afecc5f35f2
https://gyazo.com/804601f30ee1df0a2df805d283f55812

**Comment by antleblanc** [comment]
Hi @Knife015! Thanks for reporting us this bug.

According to the URL provided on the description, we tested the access to a **VPS Dashboard**.
Unfortunately we were not able to reproduce the issue (same with **IPs** section mentioned on the Title).

Based on our tests, both **VPS Dashboard** and **IPs** sections are reachable.

Could you please confirm that you are still able to reproduce the bug?

Thank you!

**Comment by Knife015** [comment]
I don't know for sure what it could be, I just enter the password in ca.ovh.com and when the dashboard opens I don't even get the option to change the language and it appears in French, I live in the United States.

The weird thing is that if I open the dashboard from my mobile phone (iPhone Xs Max) it lets me change the language and browse the entire OVH page.

It also does not let me renew the services from the computer and I have already formatted and / or used different browsers, the same thing happens to me in Opera, Chrome, Internet Explorer, Microsoft Edge and some others

I leave this pictures
Chrome:
https://gyazo.com/7edb07a193f32744945c07cb27ec5cac
Microsoft Edge:
https://gyazo.com/e6054e33a9361db9d25920f7f2997265

And this happend when i clic on change language
https://gyazo.com/46beb6004c09f1d0769998309c4e1781

**Comment by Knife015** [comment]
Hi @antleblanc! Thanks for answer the report and good morning.

I don't know for sure what it could be, I just enter the password in ca.ovh.com and when the dashboard opens I don't even get the option to change the language and it appears in French, I live in the United States.

The weird thing is that if I open the dashboard from my mobile phone (iPhone Xs Max) it lets me change the language and browse the entire OVH page.

It also does not let me renew the services from the computer and I have already formatted and / or used different browsers, the same thing happens to me in Opera, Chrome, Internet Explorer, Microsoft Edge and some others

I leave this pictures
Chrome:
https://gyazo.com/7edb07a193f32744945c07cb27ec5cac
Microsoft Edge:
https://gyazo.com/e6054e33a9361db9d25920f7f2997265

And this happend when i clic on change language
https://gyazo.com/46beb6004c09f1d0769998309c4e1781

**Comment by Knife015** [comment]
Well, here I show the console log of the Google Chrome browser, the same happens in all the other browsers and I have not been able to access my OVH Dashboard since the new interface update to the OVH Manager

I keep seeing everything in French, I don't know if my account will have problems but it is difficult for me to manage the client area from my mobile.

[ca.ovh.com-1607199821286.log](https://github.com/ovh/manager/files/5647820/ca.ovh.com-1607199821286.log)
