### ISSUE TITLE
Guide for translation/internationalisation (i18n)

### ISSUE THREAD

**Issue by maclermo** [ovh/manager#4079]
I would like to know if it's possible to have quick guide on how to write new translations for the manger.

I'd like to add a few languages that are currently not present in the manager. But I have no idea where to start.

Thank you.

**Comment by antleblanc** [comment]
Hi @maclermo!

> I would like to know if it's possible to have quick guide on how to write new translations for the manger.

You can find this information in the [`CONTRIBUTING.md`](https://github.com/ovh/manager/blob/master/CONTRIBUTING.md#translations) file.
We only accept Pull Request that targets French translation files (these files are named `Messages_fr_FR.json`).

For other languages, feel free to open an Issue or comment on this one and we will send it to our Translation Team.

> I'd like to add a few languages that are currently not present in the manager. But I have no idea where to start.

Could you please tell us a bit more about it? Maybe I can reach the Translation Team based on your feedback.

Thank you!

**Comment by maclermo** [comment]
Hi,

I was thinking of translating the manager to Swedish.

It makes sense since we have a decent customer customer base in sweden.

Let me know what you think.

Thank you !

**Comment by antleblanc** [comment]
Thank you @maclermo for the details!

We recently received a similar request (#3244) in order to add the :ru: **Russian**  language.
Unfortunately it's not plan to add it.

I will contact our Translation Team in order to know if the :sweden: **Swedish** could be supported or not and I will keep you posted.

:pray: Thanks

**Comment by antleblanc** [comment]
@maclermo I received a confirmation from our Translation Team.

Here is the list of language that we are currently supporting:
- French
- Italian
- Spanish
- Polish
- Portuguese
- English
- German

It's not plan to support other language from now so I'll close this Issue.

Thank you!
