### ISSUE TITLE
Stay in good public cloud project context when refreshing

### ISSUE THREAD

**Issue by mhurtrel** [ovh/manager#4089]
**Describe the bug**
 When we are on a cloud project, and we press F5 don't redirect to default cloudproject but stay in the cloud project you are working on

**To Reproduce**
Crrate multiple project. visit a subsection of one project and clicf efresh/F5.
You are moved to the same section of the default project, not the one you were working on.
**Expected behavior**
In the same section, keep working in the same public cloud project even i you refrlexh the page

**Additional context**
Come from a gitter demand :  https://gitter.im/ovh/kubernetes?at=5fbe4597abf6a739a6b46028
"@OVH, i think we can make huge improvement in OVH Interface, when we are on a cloud project, and we press F5 don't redirect to default cloud, just stay on the same cloud. In my case default cloud was production and i was removing old PV from dev cloud ... i just remove 2 pv in production by pressing F5
just create 2 clouds, Cloud 1 and cloud 2, set Cloud 1 as default
select cloud 2 in interface go in Block Storage,
press f5
now u're in block storage of cloud 1 instead of cloud 2"

**Comment by Chaya56** [comment]
I was abble to reproduce this 2 times, but was not abble to find the right conditions to reproduce this.

**Comment by anooparveti** [comment]
Hello,

Thanks for reporting an issue but it is not reproducible anymore.
Feel free to raise an issue if you feel the issue is not solved yet.

Thanks!
