### ISSUE TITLE
Typo: "Tyoe of database"

### ISSUE THREAD

**Issue by Thiht** [ovh/manager#4120]
**Describe the bug**
There's a typo in the `private_database_order_clouddb_database_type` translation for en_GB, fi_FI and lt_LT: "Tyoe of database" instead of "Type of database"

**Screenshots**
![Capture d’écran 2020-12-01 à 18 07 20](https://user-images.githubusercontent.com/2796344/100773324-ffbaab00-3400-11eb-8c02-baf53a119b08.png)

**Comment by antleblanc** [comment]
Hi @Thiht! Thanks for reporting us this typo.
