### ISSUE TITLE
Typo: "Une erreur est survenu"

### ISSUE THREAD

**Issue by Thiht** [ovh/manager#4350]
Hi,

**Describe the bug**
There's a typo in some French error messages: "Une erreur est survenu" instead of "Une erreur est survenu**e**".
See: https://github.com/ovh/manager/search?q=%22erreur+est+survenu%22

**Comment by antleblanc** [comment]
Hi @Thiht! Thanks for reporting us this issue. 

Patch will be part of our next release. We will keep you posted once it will be deployed.

Thank you!

**Comment by antleblanc** [comment]
Hi @Thiht!

We will keep you posted once the patch will be deployed.
Thank you!

**Comment by antleblanc** [comment]
Hi @Thiht!

Just to let you know that the release has been deployed.
Issue is now fixed.

Thank you!
