### ISSUE TITLE
The "Bare Metal Cloud" tab is active on the user account/profile page 

### ISSUE THREAD

**Issue by Thiht** [ovh/manager#4353]
**Describe the bug**
The "Bare Metal Cloud" tab is active on the user account/profile page, it's a bit confusing.

**To Reproduce**
1. Login
2. Go to this page: https://www.ovh.com/manager/dedicated/#/useraccount/dashboard

**Expected behavior**
The "Bare Metal Cloud" should not be displayed as active. Maybe the username "tab" should be active instead?

**Screenshots**
<img width="1305" alt="Capture d’écran 2021-01-27 à 16 50 05" src="https://user-images.githubusercontent.com/2796344/106016582-e4e27b00-60bf-11eb-9dbe-54600c5af64c.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Firefox
 - Version: 85

**Comment by antleblanc** [comment]
Hi @Thiht!

**Bare Metal Cloud** tab (used to be named _Server_ or _Dedicated_) is the first
Universe we've created.

In this first application we've integrated both sections that are :
- "User profile management" ;
- "Billing Services management" ;

We are actively working on converting these sections into isolated modules in
order to be able to move them around as we wish and improve the user experience.

Pending draft is here: https://github.com/ovh/manager/pull/4345

The **Bare Metal Cloud** tab will remain active for few weeks but we will keep you
posted once it will be updated.

Thank you!
