### ISSUE TITLE
telephony: event scheduler does not retreive events beginning ou ending outside specified timeframe

### ISSUE THREAD

**Issue by julieni** [ovh/manager#4362]
**Describe the bug**
Called URL is like: 	https://www.ovhtelecom.fr/engine/apiv6/telephony/xxxxxxxx/scheduler/xxxxx/events?dateEnd.to=2021-02-01&dateStart.from=2020-12-28

My event scheduled from 2021-01-29 to 2021-02-08 is not retrieved, and so not displayed in the UI.

Should make 2 requests, one with dateEnd.to=2021-02-01, the other with dateStart.from=2020-12-28, and merge results with unique filter.

**Comment by JeremyDec** [comment]
Hello @julieni,

Thanks for reporting this issue !

This bug will be addressed.

I'll keep you in touch with the resolution of the issue.

Jeremy

**Comment by antleblanc** [comment]
Hi @julieni!

We will keep you posted once the patch will be deployed.
Thank you!

**Comment by antleblanc** [comment]
Hi @julieni!

Just to let you know that the release has been deployed.
Issue is now fixed.

Thank you!

**Comment by julieni** [comment]
> Hi @julieni!
> 
> Just to let you know that the release has been deployed.
> Issue is now fixed.
> 
> Thank you!

:+1:
