### ISSUE TITLE
New PCI feature to disable quota auto scaling is reversed

### ISSUE THREAD

**Issue by reenjii** [ovh/manager#5358]
**Describe the bug**
New PCI feature to disable quota auto scaling is reversed.

**To Reproduce**
Go to Public Cloud, Quota & Regions, Quota autoscaling toggle.

**Expected behavior**
Should PUT manualQuota to false when enabled, and manualQuota to true when disabled on this call.
https://api.ovh.com/console/#/cloud/project/%7BserviceName%7D#PUT

**Comment by antleblanc** [comment]
Thanks for reporting us this issue @reenjii!
