### ISSUE TITLE
Public Cloud: Billing Control showing incorrect language

### ISSUE THREAD

**Issue by HNGamingUK** [ovh/manager#5474]
**Describe the bug**
Even with the English language selected in the top right of the manager when going to the billing control under Public Cloud the majority of the page is in French. 

**To Reproduce**
1. Open OVH Manager
2. Ensure English is selected in top right
3. Go to "Public Cloud"
4. Select "Billing Control"

**Expected behaviour**
Billing Control page will have French text instead of English

**Screenshots**
![image](https://user-images.githubusercontent.com/5269015/131935168-1ce6f451-d33d-4fb4-8bbc-66a0cc540fa4.png)
![image](https://user-images.githubusercontent.com/5269015/131935186-309a2b4d-fd64-47f0-bf33-69f0c45c23f8.png)
![image](https://user-images.githubusercontent.com/5269015/131935239-7168a42c-2652-46b2-a1f9-9761c25a7284.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Brave
 - Version 1.28.106

**Comment by antleblanc** [comment]
Hi @HNGamingUK!

Patch has been deployed. Translations are now displayed correctly.

Thanks for your feedback!
