### ISSUE TITLE
Public Cloud: Object Storage & Cloud Archive oops page shows once

### ISSUE THREAD

**Issue by HNGamingUK** [ovh/manager#5476]
**Describe the bug**
On initial load of the manager and attempting to create a object storage or cloud archive container you get an oops an error occurred page. After clicking try again it works fine. 

**To Reproduce**
1. Login to Manager
2. Open Public Cloud
3. Attempt to create Object Storage or Cloud Archive container

**Expected behavior**
Create container page loads without issue

**Screenshots**
![image](https://user-images.githubusercontent.com/5269015/131984141-8f7ee3e2-6ed7-4384-8186-56118e72d02a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser All
 - Version All

**Additional context**
I have also noticed after clicking try again but switching to instances it can then sometimes cause the error to happen again when attempting to create a new Object Storage or Cloud Archive container.

**Comment by antleblanc** [comment]
Hi @HNGamingUK!

Thanks for reporting us this issue.

According to the steps defined above, you should see this page:
![image](https://user-images.githubusercontent.com/428384/135661747-1d008b48-4b4d-4f68-b1b2-d73c11e5db33.png)

Once you click on "**Create a volume**", you are redirected to:
https://www.ovh.com/manager/public-cloud/#/pci/projects/PROJECT_ID/storages/blocks/new

Are you still able to reproduce this issue?

Regards,
Antoine

**Comment by HNGamingUK** [comment]
> Hi @HNGamingUK!
> 
> Thanks for reporting us this issue.
> 
> According to the steps defined above, you should see this page: ![image](https://user-images.githubusercontent.com/428384/135661747-1d008b48-4b4d-4f68-b1b2-d73c11e5db33.png)
> 
> Once you click on "**Create a volume**", you are redirected to: https://www.ovh.com/manager/public-cloud/#/pci/projects/PROJECT_ID/storages/blocks/new
> 
> Are you still able to reproduce this issue?
> 
> Regards, Antoine

Thanks for the reply, I am currently unable to reproduce the issue but it has happened a few times. 

The page will load with the error I originally posted and on pressing try again it will load the screen you have screenshotted.

Since writing this issue I have moved to Fedora and have not seen the error show. I will keep an eye on this but it could be resolve now.
