### ISSUE TITLE
Domain operation not working

### ISSUE THREAD

**Issue by teejayx6** [ovh/manager#5570]
I bought a domain and this is what it says 
![image](https://user-images.githubusercontent.com/89560897/133872092-22bff47e-5890-440c-8040-f866669e2dfa.png)
Erreur lors de la crÃ©ation du nom de domaine auprÃ¨s du registre
it charged me customer support is very slow

**Comment by Teejayx6** [comment]
It also logs me out of my account when i try to do certain actions

**Comment by antleblanc** [comment]
Hi @teejayx6!

Unfortunately there's nothing we can do regarding your domain operation from here.
Please contact our support team who will be able to help you or refer to https://help.ovhcloud.com.

Regards,
Antoine
