### ISSUE TITLE
Broken page design on payment successful page

### ISSUE THREAD

**Issue by zmilonas** [ovh/manager#5660]
**Describe the bug**
The payment successful page on the polish domain seems to be broken and has really weird mix of "old design" and new design

**To Reproduce**
1. Go to manager
2. Click on a domain
3. Start the renewal flow
4. Renew the domain
5. Pay by registered card
6. See weird page

**Expected behavior**
I would expect a page with more uniform design and legible menus

**Screenshots**
<img width="1309" alt="Zrzut ekranu 2021-09-30 o 15 24 29" src="https://user-images.githubusercontent.com/25948390/135454665-136f41af-1f48-4e3d-8805-87857ae01ab3.png">

**Desktop (please complete the following information):**
Safari 15 on macOS

here's the url:
https://www.ovh.pl/cgi-bin/order/payWithRegistered.cgi?paymentMeanId=CREDIT_CARD%3A34<snip>

**Comment by antleblanc** [comment]
Hi @zmilonas!

Thanks for reporting us this issue.

I will contact the right team in order to report it this issue.
We will keep you posted once it's fixed.

Thank you!

**Comment by antleblanc** [comment]
Hi @zmilonas!

A patch has been deployed. Issue should be now fixed.

Thank you!
