### ISSUE TITLE
Can't create API keys 🐛 :bug: 

### ISSUE THREAD

**Issue by seba9999** [ovh/manager#5945]
### Discussed in https://github.com/ovh/manager/discussions/5944

<div type='discussions-op-text'>

<sup>Originally posted by **seba9999** November 10, 2021</sup>
Hello I'm trying to play with the API but can't create my API keys ... 

This site https://eu.api.ovh.com/createToken/  give me an annoying "Invalid account / password". 

But I'm able to play around with the API with the web version because I can authentify at https://eu.api.ovh.com/auth/ 

What do I miss ?

Btw I've also "activated" the "developer options" in my OVH account (Which talks about API....) 

PS : trying to follow the "advanced" part of this [official tutorial](https://docs.ovh.com/gb/en/api/first-steps-with-ovh-api/#advanced-usage-pair-ovhcloud-apis-with-an-application_2)</div>

**Comment by antleblanc** [comment]
Hi @seba9999!

You can refer to following comment:
https://github.com/ovh/manager/discussions/5944#discussioncomment-1699965

**Comment by seba9999** [comment]
I'll try that ASAP
