### ISSUE TITLE
Dedicated Servers - OS Installation List - OS are grouped by type (Windows, Linux, Unix, etc.) but not sorted

### ISSUE THREAD

**Issue by JayBeeDe** [ovh/manager#5951]
**Describe the bug**
Dedicated server OS types list not sorted.

**To Reproduce**
1. Go to 'Bare Metal Cloud' tab
2. Click on 'Dedicated servers'
3. Choose a server
4. In 'General Information' section, in front of the 'System  (OS)' sub-section, click the three dots '...' and then 'Install'
5. Then choose 'Install from an OVHcloud template'
6. Choose 'Virtualization' usage
7. You have the following order: Windows, Linux, Unix
8. Cancel
9. Repeat step 3 to 8 on another server: order is different: Linux, Unix, Windows

**Expected behavior**
OS types should always be sorted in alphabetical order.

**Screenshots**

![image](https://user-images.githubusercontent.com/17429937/141492576-ecd1a45e-b50e-4fc2-9693-aafe6be20ce6.png)
![image](https://user-images.githubusercontent.com/17429937/141492249-d9e51c49-fd26-4229-88b8-f9041b374295.png)

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu 20
 - Browser:  Chromium
 - Version: 95.0.4638.69

**Comment by JayBeeDe** [comment]
Note that the issue could also occur while choosing "Install one of your templates" instead of choosing "Install from an OVHcloud template"

**To Reproduce**
Steps to reproduce the behavior:
1. Go to 'Bare Metal Cloud' tab
2. Click on 'Dedicated servers'
3. Choose a server
4. In 'General Information' section, in front of the 'System  (OS)' sub-section, click the three dots '...' and then 'Install'
5. Then choose 'Install one of your templates'
6. You have the following order: Linux, Windows
7. Cancel
8. Repeat step 3 to 7 on another server: order is different: Windows, Linux

(could not reproduce it because I don't have enough personal template other than Linux)

**Screenshots**
![image](https://user-images.githubusercontent.com/17429937/141493385-ecb62696-f3dd-4dfa-8531-3862b99abfb7.png)

**Comment by anooparveti** [comment]
This PR has been proded with MANAGER-10227
