### ISSUE TITLE
Failed to make payments

### ISSUE THREAD

**Issue by arunvc** [ovh/manager#6042]
Fail to make VPS server payment via credit card.
[500 ]: "Internal server error"
CA.manager-2.61a3bb37.16872.9d04e8e7-5d67-48fd-8933-8cc6e7be10d3

**Screenshots**
![image](https://user-images.githubusercontent.com/9069988/143779346-71719a44-4605-4b00-90d1-72e3e2f4efee.png)

**Desktop (please complete the following information):**
 - OS: [Ubuntu 20.04
 - Browser [chrome, firefox]
 - Version [latest]

**Comment by antleblanc** [comment]
Hi @arunvc!

Unfortunately there's nothing we can do regarding your order from here.
Please contact our support team who will be able to help you or refer to https://help.ovhcloud.com.

Thank you!
