### ISSUE TITLE
2FA prompt not showing

### ISSUE THREAD

**Issue by diveyez** [ovh/manager#6109]
**Describe the bug**
The 2fa prompt is not showing on login.

**To Reproduce**
Attempt ovh manager login
2FA does not show

**Expected behavior**
2FA prompt.

**Screenshots**

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A
**Additional context**

I have become entirely locked out of my account because of this bug, and the support on the telephone and in the emails cannot help me because they do not speak or type well.

**Comment by JeremyDec** [comment]
Hello @diveyez,

Unfortunately there's nothing we can do regarding your account from here, as it is hard to investigate on your case without proper information.

What kind of 2FA prompt should you have? Application Code? Other?

I'll suggest you to try again to reach support teams through https://help.ovhcloud.com.

Thank you!
