### ISSUE TITLE
Internal Server Error on manager & api for dedicated server

### ISSUE THREAD

**Issue by Nemykal** [ovh/manager#6344]
**Describe the bug**
Currently getting this error message when I browse to https://ca.ovh.com/manager/dedicated/#/server and click my server name:
```
An error has occurred loading the page.
Internal server error
```

When I try the API explorer at https://ca.api.ovh.com/console/#/dedicated/server#GET I noticed I get a similar error on a few endpoints for example /dedicated/server/{serviceName}/features/ipmi/access
`Internal Server Error (500){ "message": "Internal server error" }`

It also happens on PUTs for  /dedicated/server/{serviceName} if I try to change the boot device remotely. 

```Response
HTTP/1.1 500 Internal Server Error
Access-control-allow-headers:
X-Ovh-Timestamp, X-Ovh-Consumer, X-Ovh-Application, X-Ovh-Signature, X-Ovh-Session, Authorization, Content-Type
Access-control-allow-methods:
GET, PUT
Access-control-allow-origin:
*
Cache-control:
no-cache, no-store
Content-type:
application/json; charset=utf-8
Date:
Mon, 24 Jan 2022 08:07:30 GMT
X-content-type-options:
nosniff
X-frame-options:
DENY
X-iplb-instance:
28999
X-iplb-request-id:
CA99D31B:2A2E_C61B5B43:01BB_61EE5E41_167717:2164E
X-ovh-queryid:
CA.ext-4.61ee5e42.2548.f3edc178-2101-4a90-9d2b-f8506dfc2344
X-xss-protection:
1; mode=block
{
  "message": "Internal server error"
}
```

**Comment by JeremyDec** [comment]
Hello @Nemykal, 

There are currently Incident tickets opened that report the issue.
It will be investigated by the teams in charge of this API as soon as possible.

I'll keep you in touch

Thanks

**Comment by Nemykal** [comment]
https://bare-metal-servers.status-ovhcloud.com/incidents/gw4jbj95md35

Looks like this is the incident tracker. I hope this can be fixed soon, since I can't access the dedicated server IPMI KVM

**Comment by JeremyDec** [comment]
Hello @Nemykal,

I'm closing this issue since last answer for the fix deployed, feel free to re-open it.

Jeremy
