### ISSUE TITLE
OVH Manager errors - dedicated servers, tickets

### ISSUE THREAD

**Issue by drooJV** [ovh/manager#6703]
in OVH Manager, unable to see dedicated servers, VPS or even open or check support tickets.
Looks similar to: https://bare-metal-servers.status-ovhcloud.com/incidents/gw4jbj95md35

Errors I receive when logged and trying to access some pages:
===================================
Oops!
An error has occurred loading the page.
===================================
An error has occurred loading the page.
Error code: CA.manager-2.6231eb31.15469.f624b44c-3716-4ca7-abe2-281e92578029

**Comment by JeremyDec** [comment]
Hello @drooJV, the mentioned incident has been resolved, and therefore I've been able to access to your account, and browse to your services.

Thus, I'll close this issue.

Feel free to re-open it if something goes wrong again when accessing your account.

Thanks,
Jeremy
