### ISSUE TITLE
DOMAIN OWNER NOT VISIBLE inside ovh control panel

### ISSUE THREAD

**Issue by Maurozio** [ovh/manager#6731]
There are 4 types of domain name contacts: registrant (owner), administrator, technical and billing.
Owner is the most important contact information for a domain name and it is not visible inside ovh control panel, exactly inside "Contacts Section" of the tab "General Information" of the domain name.
All ICANN Accredited Registrars's Control Panels clearly show the Owner Contact Information of a domain.
I simply don't know why OVH hides Owner Contact Information, instead of clearly showing it inside the domain management of its Control Panel.
This is a bug!
![3652-2](https://user-images.githubusercontent.com/18407327/159380695-39ab6a47-483e-42a3-b877-57ed4296c086.png)

**Comment by JeremyDec** [comment]
Hello @Maurozio,

Thanks for the issue reported here. I'll reach the stakeholders to submit the case and keep you in touch.

Jeremy

**Comment by JeremyDec** [comment]
Hello @Maurozio issue hsa been fixed.
