### ISSUE TITLE
"Buy Public Cloud credit" disappears

### ISSUE THREAD

**Issue by adiantek** [ovh/manager#7180]
### Have you already contacted our help centre?

- [ ] Yes, I have contacted the help centre.

### Is there an existing issue for this?

- [X] I have checked the existing issues

### Describe the bug

If you want to select "Amount to credit (ex. VAT)" it disappears sometimes

### Steps To Reproduce

1. Click mouse down on input with the amount
2. Drag mouse outside modal
3. Mouse up after dragging
4. Modal disappears
https://youtu.be/IE4843eCpr4

### Expected Behavior

Modal should not disappear

### What browsers are you using?

Chrome

### Which devices are used?

Desktop

**Comment by JeremyDec** [comment]
Hello @adiantek,

Thanks for your report!

It seems to be a known issue related to Chrome (or Chromium) browser, and does not occurs on other browsers.

I'll try to check if we can make a fix  or find a workaround on our side.

Jeremy

**Comment by JeremyDec** [comment]
Hello @adiantek,

As mentioned before, it is known issue (https://github.com/Semantic-Org/Semantic-UI/issues/6430).

No workaround has been found for this, I'll suggest you to follow up the mentioned issue.

Jeremy
