### ISSUE TITLE
Unable to add subdomain

### ISSUE THREAD

**Issue by Lancelotbronner** [ovh/manager#7698]
### Have you already contacted our help centre?

- [X] Yes, I have contacted the help centre.

### Is there an existing issue for this?

- [X] I have checked the existing issues

### Describe the bug

I am unable to add a subdomain to my domain. I purchased two domain names and would like to add a bunch of subdomains to them.

I am met with the message `hosting_tab_DOMAINS_configuration_add_step1_ovh_search_no_result_found`.

### Steps To Reproduce

1. Go to Domains/yourdomain.ovh
2. In the `Actions` menu to the right, select `Add sub-domain`.
3. Type the subdomain and select `Add a domain or sub-domain to your hosting plan`
4. Within the search result area, an information aside is displayed with its contents being `hosting_tab_DOMAINS_configuration_add_step1_ovh_search_no_result_found`

### Expected Behavior

I don't really know as I haven't done this before with OVH, but definitely not that~ 😆

### What browsers are you using?

Safari

### Which devices are used?

Desktop

### Additional information to add?

I bought the domains barely 30 minutes ago, could time be an issue?

I also don't have any web hosting plans as I only need redirections for all domains and subdomains, do I need them?

**Comment by Lancelotbronner** [comment]
**Note:** The order tracking now displays the product and bill as available, still unable to create subdomains.

**Comment by JeremyDec** [comment]
Hello @Lancelotbronner,

Do you have any information about a call which fails? An error in console or whatever? (Avoid sensitive information here no github)

Also, I know that you had already contact our help centre, but, if not already done, you should send them more information about your specfic domain and account.

This way we could track your issue, and investigate on it.

Thanks

**Comment by Lancelotbronner** [comment]
I'll check the console and try again! And sorry I misread *contacted* for *consulted*.

I'll post here the results in the console and open an issue with the help center!

**Comment by Lancelotbronner** [comment]
Also on a sidenote, the manager takes around 10 minutes to load on ca.ovh.com, Is this known?

**Comment by Lancelotbronner** [comment]
Update: I've reloaded a few times but the longest so far is 50 minutes and I still haven't gotten to the dashboard.

**Comment by JeremyDec** [comment]
> Also on a sidenote, the manager takes around 10 minutes to load on ca.ovh.com, Is this known?

This topic is handled by our teams, and provide effort to reduce time to load the Control panel.

 > I'll post here the results in the console and open an issue with the help center!

If it is ok for you, then we can close this issue report. Can you DM me the reference of your ticket (or your nichandle) ?

Thanks

**Comment by Lancelotbronner** [comment]
So far I haven't managed to get to the control panel to open a ticket, I'm still trying to connect every day

**Comment by JeremyDec** [comment]
@Lancelotbronner are you able to reach help centre through this link? https://help.ovhcloud.com

**Comment by Lancelotbronner** [comment]
Yes, I then went to "Contact Us", then billing and "Open a ticket", which redirected me into the control panel.

**Comment by JeremyDec** [comment]
You have also the choice to make a call if you follow the option "Call us" 

![image](https://user-images.githubusercontent.com/34273689/182546139-3c7f6312-ffd9-4b4a-8490-b59b44130e8b.png)
