### ISSUE TITLE
Dedicated Servers - Server General information - Missing Hardware Tile for legacy boot servers

### ISSUE THREAD

**Issue by JayBeeDe** [ovh/manager#8037]
### Have you already contacted our help centre?

- [ ] Yes, I have contacted the help centre.

### Is there an existing issue for this?

- [X] I have checked the existing issues

### Describe the bug

Missing "Hardware" tile on Manager-ovh for old servers.

### Steps To Reproduce

1. Go to 'Bare Metal Cloud' tab
2. Click on 'Dedicated servers'
3. Choose a server that has EFI boot
4. In 'General Information' tab, check the different tiles: "General information", "Hardware", "Service status", "Network", "Subscription", "Our advice" and "MRTG"
![image](https://user-images.githubusercontent.com/17429937/191290875-d03541c1-32d6-4b78-8208-0a9130b1dd3d.png)
5. Repeat step 3 and 4 with a server that has legacy boot: in 'General Information' tab, check the different tiles: "General information", "Service status", "Network", "Subscription", "Our advice" and "MRTG": "Hardware" tile is missing
![image](https://user-images.githubusercontent.com/17429937/191292610-25600903-9048-48d4-ba96-f59cc4e8d73e.png)

### Expected Behavior

Any server whatever the hardware is should display the "hardware" tile with the informations

### What browsers are you using?

Chrome

### Which devices are used?

Desktop

**Comment by JeremyDec** [comment]
Hi @JayBeeDe, seen together, this issue can now be closed
