### ISSUE TITLE
Logs Data Platform - OpenSearch Dashboards instances pricing

### ISSUE THREAD

**Issue by SimonRTC** [ovh/manager#8039]
### Have you already contacted our help centre?

- [ ] Yes, I have contacted the help centre.

### Is there an existing issue for this?

- [X] I have checked the existing issues

### Describe the bug

We all love free stuff! But this seem to be a display error... :(

![ovh-ldp-bug-report](https://user-images.githubusercontent.com/42247677/191326241-140ac66c-8633-48d4-a409-b40e0f47289a.png)

### Steps To Reproduce

Create new OpenSearch Dashboards on a Logs Data Platform project.

### What browsers are you using?

Chrome

### Which devices are used?

Desktop

**Comment by SimonRTC** [comment]
**_erratum_**:
### Have you already contacted our help centre?

- [X] Yes, I have contacted the help centre.

> _I mentioned this issue on a ticket opened today for multiple other reasons (ID: 6277197)._

**Comment by cbourgois** [comment]
https://github.com/ovh/manager/pull/8076 fixed this bug. 
Thanks @SimonRTC for your report & @pdepaepe for your contribution.
