### ISSUE TITLE
Delete service confirmation no longer redirects correctly

### ISSUE THREAD

**Issue by MJBGO** [ovh/manager#8469]
### Have you already contacted our help centre?

- [ ] Yes, I have contacted the help centre.

### Is there an existing issue for this?

- [X] I have checked the existing issues

### Describe the bug

Hello,

When deleting a service (in my case, an additionnal ip), the link generated and sent by email is : https://www.ovh.com/manager/#/billing/confirmTerminate?id=XXXX&token=XXXX

It was before redirecting /billing to /dedicated/billing. Now, it does not, and redirects to the invoice history page.

I think it's liked to  https://github.com/ovh/manager/commit/7122b4dde1786c75f4ef5933f1b50037243bc003

and especially : 

![image](https://user-images.githubusercontent.com/8344487/204842998-00d161c2-4f59-49c4-aa97-9af0f5494e3c.png)

I managed to remove my ips by updating manually the links ...

Can you look and fix ?

Thanks

### Steps To Reproduce

Remove a service that needs confirmation (an additionnal ip for example) and click on the link sent by email.

### What browsers are you using?

Chrome

### Which devices are used?

Desktop

**Comment by frenautvh** [comment]
Hello @MJBGO, thanks for reporting the issue, it has just been fixed
