### ISSUE TITLE
Public cloud: Double escaping of headers

### ISSUE THREAD

**Issue by FlorianLudwig** [ovh/manager#8650]
### Have you already contacted our help centre?

- [ ] Yes, I have contacted the help centre.

### Is there an existing issue for this?

- [X] I have checked the existing issues

### Describe the bug

Titles in the public cloud section are escaped twice, leading to titles like:

```
Users &amp; Roles
Contacts &amp; Rights
```

### Steps To Reproduce

open public cloud

![image](https://user-images.githubusercontent.com/432263/209943695-91970370-524b-4e91-96cb-a8b953d67515.png)

**Comment by anooparveti** [comment]
Hello,
Thanks for reporting the issue. It has been fixed in the release `manganese-cod`.
